---
deployment:
  tasks:
    - export DEPLOYPATH=/home/odingrey/www/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp undraw_dev_productivity_umsq1.svg $DEPLOYPATH
    - /bin/cp assets/guy.png $DEPLOYPATH